apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  namespace: default
  labels:
    app: goserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      name: "goserver"
      namespace: default
      labels:
        app: "goserver"
    spec:
      containers:
      - name: "goserver"
        image: "wander4747/hello-k8s"
        env:
          - name: NAME
            value: "Wander"
          - name: AGE
            value: "30"
          