apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  namespace: default
  labels:
    app: goserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      name: "goserver"
      namespace: default
      labels:
        app: "goserver"
    spec:
      containers:
      - name: "goserver"
        image: "wander4747/hello-k8s:latest"
        startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 3
            failureThreshold: 30
        readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 3
            failureThreshold: 1
        livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1

        envFrom:
          - configMapRef:
              name: goserver-env
          - secretRef:
              name: goserver-secret

        volumeMounts:
          - mountPath: "/go/src/myfamily"
            name: config

      volumes:
        - name: config
          configMap:
            name: configmap-volume
            items:
              - key: members
                path: "family.txt"
        # env:
        #   - name: NAME
        #     value: "Wander"
        #   - name: AGE
        #     value: "30"
          