apiVersion: v1
kind: Service
metadata:
  name: goserver-service
  namespace: default
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
  - name: goserver-service
    protocol: TCP
    port: 8000
    nodePort: 30001 #30000 32767