apiVersion: v1
kind: Service
metadata:
  name: goserver-service
  namespace: default
spec:
  selector:
    app: goserver
  type: LoadBalancer
  ports:
  - name: goserver-service
    protocol: TCP
    port: 8000